- name: STEP-1 REMOVE DEPRECATED ZABBIX-AGENT-2 
  hosts: [ubuntug]
  become: yes 
  tasks: 
    - name: uninstall zabbix-agent2
      apt: 
        name: [ zabbix-agent2 , zabbix-agent2-plugin-* ]
        state: absent
    - name: remove zabbix-agent-2 package file
      file:
       dest: /root/zabbix-release_6.0-4+ubuntu22.04_all.deb
       force: true
       state: absent
    - name: updating...
      raw: apt update 

- name: open firewall port on nodes
  hosts: [ubuntug]
  become: yes
  tasks:  
    - name: open firewall port
      ufw:
       rule: allow
       port: 10050,10051
       proto: tcp

- name: STEP-3 GET ZABBIX-AGENT2 REPOSITORY
  hosts: [ubuntug]
  become: yes
  tasks:
    - name: GET ZABBIX-AGENT2 (ubuntu)
      shell: wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb

    
    - name: install zabbix-agent2 (Package)
      raw: dpkg -i /root/zabbix-release_6.0-4+ubuntu22.04_all.deb 

- name: STEP-4 INSTALL ZABBIX-AGENT FROM REPOOSITORY
  hosts: [ubuntug]
  become: yes
  tasks: 
    - name: install zabbix-agent2
      apt: 
        update_cache: yes
        name: [ zabbix-agent2 , zabbix-agent2-plugin-* ]
        state: latest
    - name: start zabbix-agent-2 service
      service:
        name: zabbix-agent2
        state: started
