- name: Install Node Exporter and Blackbox Exporter
  hosts: all
  become: yes
  tasks:

    - name: set DNS!!!
      copy:
        dest: /etc/resolv.conf
        content: | 
          nameserver 8.8.8.8
          nameserver 4.4.4.4

    - name: create blackbox config file
      shell: mkdir -p /etc/blackbox_exporter

    - name: Create exporter user
      user:
        name: exporter
        shell: /sbin/nologin
        system: yes
        create_home: no
        state: present

    - name: Download node_exporter to /opt
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.10.2/node_exporter-1.10.2.linux-amd64.tar.gz
        dest: /opt/node_exporter-1.10.2.linux-amd64.tar.gz
        mode: '0644'

    - name: Download blackbox_exporter to /opt
      get_url:
        url: https://github.com/prometheus/blackbox_exporter/releases/download/v0.27.0/blackbox_exporter-0.27.0.linux-amd64.tar.gz
        dest: /opt/blackbox_exporter-0.27.0.linux-amd64.tar.gz
        mode: '0644'

    - name: Extract node_exporter
      unarchive:
        src: /opt/node_exporter-1.10.2.linux-amd64.tar.gz
        dest: /opt
        remote_src: yes

    - name: Extract blackbox_exporter
      unarchive:
        src: /opt/blackbox_exporter-0.27.0.linux-amd64.tar.gz
        dest: /opt
        remote_src: yes

    - name: copy confige file to /etc/blackbox_exporter
      copy:
        src: /opt/blackbox_exporter-0.27.0.linux-amd64/blackbox.yml
        dest: /etc/blackbox_exporter
        mode: '644'
        remote_src: yes

    - name: Copy node_exporter to /usr/local/bin
      copy:
        src: /opt/node_exporter-1.10.2.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        mode: '0744'
        owner: exporter
        group: exporter
        remote_src: yes

    - name: Copy blackbox_exporter to /usr/local/bin
      copy:
        src: /opt/blackbox_exporter-0.27.0.linux-amd64/blackbox_exporter
        dest: /usr/local/bin/blackbox_exporter
        mode: '0744'
        owner: exporter
        group: exporter
        remote_src: yes

    - name: Create node_exporter systemd service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode: '0644'
        content: |
          [Unit]
          Description=Prometheus Node Exporter
          After=network.target

          [Service]
          User=exporter
          Group=exporter
          Type=simple
          ExecStart=/usr/local/bin/node_exporter --collector.textfile.directory="/tmp/node_exporter"
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Create blackbox_exporter systemd service
      copy:
        dest: /etc/systemd/system/blackbox_exporter.service
        owner: root
        group: root
        mode: '0644'
        content: |
          [Unit]
          Description=Prometheus Blackbox Exporter
          After=network.target

          [Service]
          User=exporter
          Group=exporter
          Type=simple
          ExecStart=/usr/local/bin/blackbox_exporter --config.file=/etc/blackbox_exporter/
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start node_exporter
      systemd:
        name: node_exporter
        enabled: yes
        state: started

    - name: Enable and start blackbox_exporter
      systemd:
        name: blackbox_exporter
        enabled: yes
        state: started

